arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_shoulder_pan_joint
    - arm_shoulder_lift_joint
    - arm_elbow_flex_joint
    - arm_wrist_flex_joint
  #gains: # no effect on position based controllers, only for velocity and effort interfaces
    #arm_shoulder_lift_joint: {p: 500,  d: 10, i: 20, i_clamp: 1}

gripper_controller:
  type: "position_controllers/GripperActionController"
  joint: gripper_joint
  #goal_tolerance: 0.01
  #stalled_velocity_threshold: 0.01
  #stall_timeout: 0.2
  #gains:
  #  gripper_link_joint: {p: 200, d: 1, i: 5, i_clamp: 1}



