arm_controller:
  type: "position_controllers/JointTrajectoryController"
  #publish_rate: 10
  joints:
    - arm_elbow_flex_joint
    - arm_shoulder_lift_joint
    - arm_shoulder_pan_joint
    - arm_wrist_flex_joint


gripper_controller:
  type: "position_controllers/GripperActionController"
  joint: gripper_link_joint
  #goal_tolerance: 0.01
  #stalled_velocity_threshold: 0.01
  #stall_timeout: 0.2
  #gains:
  #  gripper_link_joint: {p: 200, d: 1, i: 5, i_clamp: 1}



