source: pincher_arm.yaml
port: /dev/ttyUSB0
rate: 10
baud: 115200
simulation: false
joints: {
    arm_elbow_flex_joint: {id: 1, cwlimit: 35,  ccwlimit: 511, speed: 60, offset: 512},
    arm_shoulder_lift_joint: {id: 2, cwlimit: 100, ccwlimit: 900, speed: 60, offset: 750},
    arm_shoulder_pan_joint: {id: 3, cwlimit: 100, ccwlimit: 900, speed: 60, offset: 0},
    arm_wrist_flex_joint: {id: 4, cwlimit: 100, ccwlimit: 900, speed: 60, offset: 0},
    gripper_link_joint: {id: 5, cwlimit: 17,  ccwlimit: 414, speed: 60, offset: 25}
}
